CUSTOM_STATUS_CODES = {
    10: {"code": 10, "message": "Match created successfully."},
    11: {"code": 11, "message": "Error occurred while creating match."},
    12: {"code": 12, "message": "Matches fetched successfully."},
    13: {"code": 13, "message": "Error occurred while fetching matches."},
    14: {"code": 14, "message": "No matches found for the given Id."},
    15: {"code": 15, "message": "Match fetched successfully."},
    16: {"code": 16, "message": "Error occurred while fetching matches."},
    17: {"code": 17, "message": "No match updated. Match may not exist or data is the same."},
    18: {"code": 18, "message": "Match updated successfully."},
    19: {"code": 19, "message": "Error occurred while updating match."},
    20: {"code": 20, "message": "Match not deleted. Match may not exist or is already deleted."},
    21: {"code": 21, "message": "Match deleted successfully."},
    22: {"code": 22, "message": "Error occurred while deleting match."},
    23: {"code": 23, "message": "player created successfully."},
    24: {"code": 24, "message": "Error occurred while creating player."},
    25: {"code": 25, "message": "players fetched successfully."},
    26: {"code": 26, "message": "Error occurred while fetching players."},
    27: {"code": 27, "message": "No player found for the given Id."},
    28: {"code": 28, "message": "player fetched successfully."},
    29: {"code": 29, "message": "Error occurred while fetching player."},
    30: {"code": 30, "message": "Player updated successfully."},
    31: {"code": 31, "message": "No fields to update."},
    32: {"code": 32, "message": "player not updated or not found"},
    34: {"code": 34, "message": "Error occurred while updating player."},
    35: {"code": 35, "message": "Player deleted successfully."},
    36: {"code": 36, "message": "Player not deleted. Player may not exist."},
    37: {"code": 37, "message": "Error occurred while deleting player."},
    38: {"code": 38, "message": "Players assigned to match successfully."},
    39: {"code": 39, "message": "Match not found or not updated."},
    40: {"code": 40, "message": "Error occurred while assigning players to match."},
    41: {"code": 41, "message": "Scoreboard created successfully."},
    42: {"code": 42, "message": "Error occurred while creating scoreboard."},
    43: {"code": 43, "message": "Scoreboard not found."},
    44: {"code": 44, "message": "Scoreboard fetched successfully."},
    45: {"code": 45, "message": "Error occurred while fetching scoreboard."},
    46: {"code": 46, "message": "Scoreboard not updated. It may not exist or no changes were made."},
    47: {"code": 47, "message": "Scoreboard updated successfully."},
    48: {"code": 48, "message": "Error occurred while updating scoreboard."},
    49: {"code": 49, "message": "Match settings updated successfully."},
    50: {"code": 50, "message": "Match not updated. Settings unchanged or match not found."},
    51: {"code": 51, "message": "Error occurred while updating match settings."},
    52: {"code": 52, "message": "Opening players not updated. Match not found."},
    53: {"code": 53, "message": "Opening players set successfully."},
    54: {"code": 54, "message": "Error occurred while setting opening players."},
    55: {"code": 55, "message": "Match not found."},
    56: {"code": 56, "message": "Ball recorded successfully."},
    57: {"code": 57, "message": "Error occurred while recording ball event."},
    58: {"code": 58, "message": "Ball events fetched successfully."},
    59: {"code": 59, "message": "Error occurred while fetching ball events."},
}
